import CountryCard from "@/components/CountryCard";
import Filter from "@/components/Filter";
import SearchCountry from "@/components/SearchCountry";
import { getAllCountries } from "@/lib/restcountries";
import { TCountry } from "@/types/country";
import Head from "next/head";
import { useState } from "react";

export async function getStaticProps() {
  const data = await getAllCountries();

  return {
    props: { data },
  };
}

type Props = {
  data: TCountry[];
};

export default function Home({ data }: Props) {
  const [countries, setCountries] = useState(data);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pt-6 mb-8 mx-4">
        <SearchCountry />
        <Filter />
      </div>
      <div className="mx-auto grid justify-items-center gap-10 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4">
        {countries?.length &&
          countries.map((country) => {
            return (
              <CountryCard
                key={country.name.official}
                capital={country.capital}
                name={country.name}
                population={country.population}
                region={country.region}
                flag={country.flags.svg}
              />
            );
          })}
      </div>
    </>
  );
}
