import { getAllCountries } from "@/lib/restcountries";
import { Country } from "@/types/country";
import Head from "next/head";
import { useState } from "react";

export async function getStaticProps() {
  const data = await getAllCountries();

  return {
    props: { data },
  };
}

type Props = {
  data: Country[];
};

export default function Home({ data }: Props) {
  const [countries, setCountries] = useState(data);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div></div>
    </>
  );
}
